/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.reportes.EstadoCuenta;
import Backend.reportes.ListadoEstadosCuenta;
import Frontend.formularios.VentanaAutorizacionTarjeta;
import Frontend.formularios.VentanaCancelacionTarjeta;
import Frontend.formularios.VentanaConsultarTarjeta;
import Frontend.formularios.VentanaMovimientoTarjeta;
import Frontend.formularios.VentanaSolicitudTarjeta;
import Frontend.reportes.PanelEstadoCuenta;
import Frontend.reportes.VentanaEstadosCuenta;
import Frontend.reportes.VentanaListaSolicitudes;
import Frontend.reportes.VentanaListaTarjetas;

import java.awt.GridLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 * @author melvin
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEstadoDeCuenta = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton1.setText("Solicitud de tarjetas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, -1));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton2.setText("Movimientos de tarjetas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, -1));

        jButton3.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton3.setText("Consulta tarjeta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, -1));

        jButton4.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton4.setText("Autorizacion de tarjetas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, -1));

        jButton5.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton5.setText("Cancelacion de tarjetas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("REPORTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("FORMULARIOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnEstadoDeCuenta.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        btnEstadoDeCuenta.setText("Estado de cuenta");
        btnEstadoDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoDeCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadoDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 200, -1));

        jButton8.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton8.setText("Listado de tarjetas");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 200, -1));

        jButton6.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jButton6.setText("Listado de solicitudes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoNuemero2.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaSolicitudTarjeta ventanaSolicitudTarjeta = new VentanaSolicitudTarjeta();
        ventanaSolicitudTarjeta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaMovimientoTarjeta ventanaMovimientoTarjeta = new VentanaMovimientoTarjeta();
        ventanaMovimientoTarjeta.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VentanaAutorizacionTarjeta ventanaAutorizacionTarjeta = new VentanaAutorizacionTarjeta();
        ventanaAutorizacionTarjeta.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VentanaCancelacionTarjeta ventanaCancelacionTarjeta = new VentanaCancelacionTarjeta();
        ventanaCancelacionTarjeta.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VentanaConsultarTarjeta ventanaConsultarTarjeta = new VentanaConsultarTarjeta();
        ventanaConsultarTarjeta.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        VentanaListaTarjetas ventanaListaTarjetas = new VentanaListaTarjetas();
        ventanaListaTarjetas.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        VentanaListaSolicitudes ventanaListaSolicitudes = new VentanaListaSolicitudes();
        ventanaListaSolicitudes.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnEstadoDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
//        VentanaEstadosCuenta ventanaEstadosCuenta = new VentanaEstadosCuenta();
//        ventanaEstadosCuenta.setVisible(true);

        JFrame frameReporte = new JFrame("Estados de cuenta de tarjetas activas");
        //frameReporte.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameReporte.setSize(600, 400); // Ajusta el tamaño según tus necesidades
        // Crea un JPanel con un GridLayout para contener los PanelEstadoCuenta
        JPanel panelContainer = new JPanel();
        panelContainer.setLayout(new GridLayout(0, 1)); // 0 para filas automáticas y 1 columna

        ListadoEstadosCuenta listadoEstadosCuenta = new ListadoEstadosCuenta();
        List<EstadoCuenta> estadosCuenta = listadoEstadosCuenta.obtenerEstadosCuenta();

        for (EstadoCuenta estadoCuenta : estadosCuenta) {
            PanelEstadoCuenta panelEstadoCuenta = new PanelEstadoCuenta();
            panelEstadoCuenta.llenarCampos(estadoCuenta);
            panelContainer.add(panelEstadoCuenta);
        }
        // Crea un JScrollPane y agrega el panelContainer a él
        JScrollPane scrollPane = new JScrollPane(panelContainer);
        frameReporte.add(scrollPane);
        frameReporte.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadoDeCuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
